version: '2'

services:
    mariadb:
    image: mariadb
    volumes:
    restart: always
    ports:
    build:
        context:
        dockerfile: 
    networks:
        inception:
    env_file: .env

volumes:
    mariadb:

    wordpress:

networks:
    inception:
        driver: bridge