/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddedToRoom: typeof import('./src/components/notifications/chat/MemberJoinedChatRoom.vue')['default']
    AvatarBadge: typeof import('./src/components/profile/AvatarBadge.vue')['default']
    Awards: typeof import('./src/components/profile/Awards.vue')['default']
    ChallengeModal: typeof import('./src/components/game/ChallengeModal.vue')['default']
    ChatConversationTopBar: typeof import('./src/components/chatRooms/ChatConversationTopBar.vue')['default']
    ChatUserProfileSidebar: typeof import('./src/components/chatRooms/ChatUserProfileSidebar.vue')['default']
    CoalitionFlag: typeof import('./src/components/profile/CoalitionFlag.vue')['default']
    DoubleFactorModal: typeof import('./src/components/profile/DoubleFactorModal.vue')['default']
    FriendRequest: typeof import('./src/components/notifications/friend/FriendRequest.vue')['default']
    FriendRequestBox: typeof import('./src/components/profile/FriendRequestBox.vue')['default']
    Friends: typeof import('./src/components/profile/Friends.vue')['default']
    GameChallengeAccepted: typeof import('./src/components/notifications/game/GameChallengeAccepted.vue')['default']
    GameChallengeRejected: typeof import('./src/components/notifications/game/GameInvitationRejected.vue')['default']
    GameInvitation: typeof import('./src/components/notifications/game/GameInvitation.vue')['default']
    GameJoined: typeof import('./src/components/notifications/game/JoinedGame.vue')['default']
    GamePaused: typeof import('./src/components/notifications/game/GamePaused.vue')['default']
    GameResumed: typeof import('./src/components/notifications/game/GameResumed.vue')['default']
    GameStatusBadge: typeof import('./src/components/game/GameStatusBadge.vue')['default']
    Greetings: typeof import('./src/components/profile/Greetings.vue')['default']
    Histories: typeof import('./src/components/profile/Histories.vue')['default']
    JoinedGame: typeof import('./src/components/notifications/game/JoinedGame.vue')['default']
    MessageContact: typeof import('./src/components/messages/MessageContact.vue')['default']
    MessageTopBar: typeof import('./src/components/messages/MessageTopBar.vue')['default']
    NavSearchBar: typeof import('./src/components/navbar/NavSearchBar.vue')['default']
    Notification: typeof import('./src/components/notifications/Notification.vue')['default']
    NotificationButton: typeof import('./src/components/navbar/NotificationButton.vue')['default']
    NotificationPopUp: typeof import('./src/components/notifications/NotificationPopUp.vue')['default']
    PlayerSimpleStats: typeof import('./src/components/profile/PlayerSimpleStats.vue')['default']
    PlayingButton: typeof import('./src/components/navbar/PlayingButton.vue')['default']
    ProfileHeader: typeof import('./src/components/profile/ProfileHeader.vue')['default']
    RequestAccepted: typeof import('./src/components/notifications/friend/RequestAccepted.vue')['default']
    RequestRejected: typeof import('./src/components/notifications/friend/RequestRejected.vue')['default']
    RoomAdministrator: typeof import('./src/components/notifications/chat/PromotedInRoom.vue')['default']
    RoomCard: typeof import('./src/components/chatRooms/RoomCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/profile/StatusBadge.vue')['default']
    TopsChatCard: typeof import('./src/components/chatRooms/TopsChatCard.vue')['default']
    UserProfileButton: typeof import('./src/components/navbar/UserProfileButton.vue')['default']
  }
}
